name: indonesia_guide
description: An app named, Indonesia Paradise, to help small business growing among international tourist.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  lottie: ^1.4.2
  widget_and_text_animator: ^1.0.9
  cloud_firestore: ^3.1.5
  flutter_lorem: ^2.0.0
  carousel_slider: ^4.1.1
  flutter_bounceable: ^1.0.3
  smooth_page_indicator: ^1.0.0+2
  flutter_rating_bar: ^4.0.1
  flutter_launcher_icons: ^0.10.0
  double_back_to_close_app: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/google_fonts/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_playstore.png"
  adaptive_icon_background: "assets/ic_playstore.png"
